export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const UPDATE_USER_INFO = "UPDATE_USER_INFO";

export const FETCH_POST_LIST = "FETCH_POST_LIST";

export const FETCH_USER_DATA = "FETCH_USER_DATA";

export const FETCH_POST_DATA = "FETCH_POST_DATA";
export const FETCH_BLOG_LIST = "FETCH_BLOG_LIST";
export const FETCH_BLOG_DATA = "FETCH_BLOG_DATA";
export const FETCH_COMIC_LIST = "FETCH_COMIC_LIST";
export const FETCH_MANGA_LIST = "FETCH_MANGA_LIST";
export const FETCH_COMIC_DATA = "FETCH_COMIC_DATA";
export const FETCH_MANGA_DATA = "FETCH_MANGA_DATA";


export const FETCH_ARTIST_USER_DATA = "FETCH_ARTIST_USER_DATA";
export const FETCH_CATEGORY_LIST = "FETCH_CATEGORY_LIST";