export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const UPDATE_USER_INFO = "UPDATE_USER_INFO";

export const FETCH_POST_LIST = "FETCH_POST_LIST";

export const FETCH_USER_DATA = "FETCH_USER_DATA";

export const FETCH_POST_DATA = "FETCH_POST_DATA";
export const FETCH_BLOG_LIST = "FETCH_BLOG_LIST";
export const FETCH_BLOG_DATA = "FETCH_BLOG_DATA";
export const FETCH_COMIC_LIST = "FETCH_COMIC_LIST";
export const FETCH_MANGA_LIST = "FETCH_MANGA_LIST";
export const FETCH_COMIC_DATA = "FETCH_COMIC_DATA";
export const FETCH_MANGA_DATA = "FETCH_MANGA_DATA";

export const FETCH_ARTIST_USER_DATA = "FETCH_ARTIST_USER_DATA";
export const FETCH_CATEGORY_LIST = "FETCH_CATEGORY_LIST";
export const FETCH_PROFILE_DATA = "FETCH_PROFILE_DATA";
export const FETCH_MANGA_CHAPTER = "FETCH_MANGA_CHAPTER";

export const POST_BLOG_COMMENT = "POST_BLOG_COMMENT";
export const LIKE_BLOG = "LIKE_BLOG";
export const UNLIKE_BLOG = "UNLIKE_BLOG";
export const POST_BLOG_REPLY = "POST_BLOG_REPLY";
export const DELETE_BLOG_COMMENT = "DELETE_BLOG_COMMENT";
export const EDIT_BLOG_COMMENT = "EDIT_BLOG_COMMENT"
export const EDIT_BLOG_REPLY = "EDIT_BLOG_REPLY"
export const DELETE_BLOG_REPLY = "DELETE_BLOG_REPLY";

export const POST_POST_COMMENT = "POST_POST_COMMENT";
export const LIKE_POST = "LIKE_POST";
export const UNLIKE_POST = "UNLIKE_POST";
export const POST_POST_REPLY = "POST_POST_REPLY";
export const DELETE_POST_COMMENT = "DELETE_POST_COMMENT";
export const EDIT_POST_COMMENT = "EDIT_POST_COMMENT"
export const EDIT_POST_REPLY = "EDIT_POST_REPLY"
export const DELETE_POST_REPLY = "DELETE_POST_REPLY";

export const ADD_POST = "ADD_POST";
export const ADD_BLOG = "ADD_BLOG";
export const ADD_MANGA = "ADD_MANGA";
export const ADD_COMIC = "ADD_COMIC";

export const DELETE_POST = "DELETE_POST";
export const DELETE_BLOG = "DELETE_BLOG";
export const DELETE_COMIC = "DELETE_COMIC";
export const DELETE_MANGA = "DELETE_MANGA";

export const POST_MANGA_COMMENT = "POST_MANGA_COMMENT";
export const RATE_MANGA = "RATE_MANGA";
export const REMOVE_MANGA_RATING = "REMOVE_MANGA_RATING";
export const POST_MANGA_REPLY = "POST_MANGA_REPLY";
export const DELETE_MANGA_COMMENT = "DELETE_MANGA_COMMENT";
export const EDIT_MANGA_COMMENT = "EDIT_MANGA_COMMENT"
export const EDIT_MANGA_REPLY = "EDIT_MANGA_REPLY"
export const DELETE_MANGA_REPLY = "DELETE_MANGA_REPLY";

